const images = [
  {
    src: '/image.png',
    alt: 'Serene Landscape',
    width: 140,
    height: 100,
    title: 'Mountain Vista',
    description: 'A breathtaking view of snow-capped mountains reflecting in a crystal-clear lake.',
    category: 'Nature',
  },
  {
    src: '/image.png',
    alt: 'Urban Architecture',
    width: 100,
    height: 75,
    title: 'City Skyline',
    description: 'Modern skyscrapers piercing the sky at golden hour, showcasing urban beauty.',
    category: 'Architecture',
  },
  {
    src: '/image.png',
    alt: 'Wildlife Portrait',
    width: 100,
    height: 130,
    title: 'Majestic Lion',
    description: 'A close-up portrait of a lion, capturing its regal and powerful essence.',
    category: 'Wildlife',
  },
  {
    src: '/image.png',
    alt: 'Abstract Art',
    width: 100,
    height: 200,
    title: 'Colorful Chaos',
    description: 'An explosion of vibrant colors in an abstract composition, evoking emotion and energy.',
    category: 'Art',
  },
  {
    src: '/image.png',
    alt: 'Culinary Delight',
    width: 100,
    height: 150,
    title: 'Gourmet Spread',
    description: 'A mouthwatering display of artisanal cheeses, fruits, and wine on a rustic wooden table.',
    category: 'Food',
  },
  {
    src: '/image.png',
    alt: 'Fashion Photography',
    width: 140,
    height: 250,
    title: 'Haute Couture',
    description: 'A striking fashion model showcasing an avant-garde design on a Parisian runway.',
    category: 'Fashion',
  },
  {
    src: '/image.png',
    alt: 'Fashion Photography',
    width: 140,
    height: 250,
    title: 'Haute Couture',
    description: 'A striking fashion model showcasing an avant-garde design on a Parisian runway.',
    category: 'Fashion',
  },
  {
    src: '/image.png',
    alt: 'Fashion Photography',
    width: 140,
    height: 250,
    title: 'Haute Couture',
    description: 'A striking fashion model showcasing an avant-garde design on a Parisian runway.',
    category: 'Fashion',
  },  
];

export default images;
